# labSistemas
Projeto do laboratório de desenvolvimento de sistemas - IFSP Guarulhos

## Banco de dados LABSISTEMAS ##

## Criação do banco de dados e as tabelas ##
CREATE DATABASE LABSISTEMAS;

USE LABSISTEMAS;


CREATE TABLE `PESSOA_FISICA` (
	`ID_PI` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`CPF_FUNC` varchar(14) NOT NULL UNIQUE,
	`NOME_FUNC` varchar(30) NOT NULL,
	`SOBRENOME_FUNC` varchar(60) NOT NULL,
	`NASCIMENTO_FUNC` DATE NOT NULL,
	`CARGO_FUNC` varchar(60) NOT NULL,
	`LOJA_FUNC` bigint NOT NULL,
	`SALARIO_FUNC` FLOAT NOT NULL
);



CREATE TABLE `LOJAS` (
	`ID_LOJA` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`ENDERECO_LOJA` varchar(150) NOT NULL,
	`ENDERECO_NUM_LOJA` bigint NOT NULL,
	`CNPJ_LOJA` varchar(19) NOT NULL UNIQUE,
	`TELEFONE_LOJA` varchar(12) NOT NULL,
	`EMAIL_LOJA` varchar(50) NOT NULL
	
);

CREATE TABLE `LOGIN_LOJA` (
	`ID_LOGIN` bigint NOT NULL AUTO_INCREMENT,
	`SENHA_LOJA` varchar(150) NOT NULL,
	PRIMARY KEY (`ID_LOGIN`)
);

CREATE TABLE `LOGIN_ADM` (
	`ID_LOGIN_ADM` bigint NOT NULL AUTO_INCREMENT,
	`USER_ADM` varchar(100) NOT NULL UNIQUE,
	`SENHA_ADM` varchar(150) NOT NULL,
	PRIMARY KEY (`ID_LOGIN_ADM`)
);



CREATE TABLE `FABRICANTE` (
	`ID_FABRICANTE` bigint NOT NULL AUTO_INCREMENT,
	`RAZAO_SOCIAL_FABRICANTE` varchar(254) NOT NULL,
	`NOME_FANTASIA_FABRICANTE` varchar(254) NOT NULL,
	`CNPJ_FABRICANTE` varchar(19) NOT NULL,
	`NUM_RUA_FABRICANTE` bigint NOT NULL,
	`ENDERECO_FABRICANTE` varchar(150) NOT NULL,
	`TELEFONE_FABRICANTE` varchar(12) NOT NULL,
	`EMAIL_FABRICANTE` varchar(50) NOT NULL,
	`OBSERVACAO_FABRICANTE` varchar(250),
	PRIMARY KEY (`ID_FABRICANTE`)
);

CREATE TABLE `ESTOQUE` (
	`ID_ESTOQUE` bigint NOT NULL AUTO_INCREMENT,
	`EAN_PRODUTO` bigint NOT NULL,
	`NOME_PRODUTO` varchar(100) NOT NULL,
	`PRECO_PRODUTO` FLOAT NOT NULL,
	`CUSTO_PRODUTO` FLOAT NOT NULL,
	`VALIDADE_PRODUTO` DATE NOT NULL,
	`FABRICACAO_PRODUTO` DATE NOT NULL,
	`ID_FABRICANTE` bigint NOT NULL,
	PRIMARY KEY (`ID_ESTOQUE`)
);



ALTER TABLE `PESSOA_FISICA` ADD CONSTRAINT `PI_LOJAS_FK0` FOREIGN KEY (`LOJA_FUNC`) REFERENCES `LOJAS` (`ID_LOJA`);

ALTER TABLE `LOGIN_LOJA` ADD CONSTRAINT `LOGIN_LOJA_fk0` FOREIGN KEY (`ID_LOGIN`) REFERENCES `LOJAS`(`ID_LOJA`);

ALTER TABLE `ESTOQUE` ADD CONSTRAINT `ESTOQUE_fk0` FOREIGN KEY (`ID_FABRICANTE`) REFERENCES `FABRICANTE`(`ID_FABRICANTE`);



CREATE VIEW CARGO_FUNCIONARIO
AS SELECT 
	PESSOA_FISICA.ID_PI AS MATRICULA,
	PESSOA_FISICA.NOME_FUNC AS NOME,
    PESSOA_FISICA.SOBRENOME_FUNC AS SOBRENOME,
    PESSOA_FISICA.CARGO_FUNC AS CARGO,
    PESSOA_FISICA.LOJA_FUNC AS LOJA
FROM PESSOA_FISICA;


SELECT * FROM CARGO_FUNCIONARIO ;


/*======================================================*/

CREATE VIEW DADOS_PRODUTO
AS SELECT 
	ESTOQUE.ID_ESTOQUE AS CODIGO_INTERNO, 
    ESTOQUE.EAN_PRODUTO AS CODIGO_BARRA,
    ESTOQUE.NOME_PRODUTO AS NOME_PRODUTO,
    ESTOQUE.PRECO_PRODUTO AS PRECO_PRODUTO,
    ESTOQUE.CUSTO_PRODUTO AS CUSTO_PRODUTO,
   (ESTOQUE.PRECO_PRODUTO / ESTOQUE.CUSTO_PRODUTO) AS LUCRO
    FROM ESTOQUE;

SELECT * FROM DADOS_PRODUTO;





