
CREATE DATABASE LABSISTEMAS;

USE LABSISTEMAS;


CREATE TABLE `PESSOA_FISICA` (
	`ID_PI` bigint NOT NULL AUTO_INCREMENT,
	`CPF_FUNC` varchar(14) NOT NULL UNIQUE,
	`NOME_FUNC` varchar(30) NOT NULL,
	`SOBRENOME_FUNC` varchar(60) NOT NULL,
	`NASCIMENTO_FUNC` DATE NOT NULL,
	`CARGO_FUNC` varchar(60) NOT NULL,
	`LOJA_FUNC` bigint NOT NULL,
	`SALARIO_FUNC` FLOAT NOT NULL,
	PRIMARY KEY (`ID_PI`)
);

CREATE TABLE `FUNCIONARIO` (
	`ID_FUNC` bigint NOT NULL,
	`CPF_FUCN` varchar(14) NOT NULL UNIQUE,
	`NOME_FUNC` varchar(30) NOT NULL,
	`SOBRENOME_FUNC` varchar(50) NOT NULL,
	`NASCIMENTO_FUNC` DATE NOT NULL
);

CREATE TABLE `CARGO` (
	`ID_CARGO` bigint NOT NULL,
	`CARGO_FUNC` varchar(60) NOT NULL,
	`LOJA_FUNC` int NOT NULL,
	`SALARIO_FUNC` FLOAT NOT NULL
);

CREATE TABLE `LOJAS` (
	`ID_LOJA` bigint NOT NULL AUTO_INCREMENT,
	`ENDERECO_LOJA` varchar(150) NOT NULL,
	`ENDERECO_NUM_LOJA` bigint NOT NULL,
	`CNPJ_LOJA` varchar(19) NOT NULL UNIQUE,
	`TELEFONE_LOJA` varchar(12) NOT NULL,
	`EMAIL_LOJA` varchar(50) NOT NULL,
	PRIMARY KEY (`ID_LOJA`)
);

CREATE TABLE `LOGIN_LOJA` (
	`ID_LOGIN` bigint NOT NULL AUTO_INCREMENT,
	`SENHA_LOJA` varchar(150) NOT NULL,
	PRIMARY KEY (`ID_LOGIN`)
);

CREATE TABLE `LOGIN_ADM` (
	`ID_LOGIN_ADM` bigint NOT NULL AUTO_INCREMENT,
	`USER_ADM` varchar(100) NOT NULL UNIQUE,
	`SENHA_ADM` varchar(150) NOT NULL,
	PRIMARY KEY (`ID_LOGIN_ADM`)
);

CREATE TABLE `PRODUTO` (
	`ID_PRODUTO` bigint NOT NULL AUTO_INCREMENT,
	`EAN_PRODUTO` bigint NOT NULL UNIQUE,
	`NOME_PRODUTO` varchar(100) NOT NULL,
	`PRECO_PRODUTO` FLOAT NOT NULL,
	`CUSTO_PRODUTO` FLOAT NOT NULL,
	`VALIDADE_PRODUTO` DATE NOT NULL,
	`FABRICACAO_PRODUTO` DATE NOT NULL,
	PRIMARY KEY (`ID_PRODUTO`)
);

CREATE TABLE `FABRICANTE` (
	`ID_FABRICANTE` bigint NOT NULL AUTO_INCREMENT,
	`RAZAO_SOCIAL_FABRICANTE` varchar(254) NOT NULL,
	`NOME_FANTASIA_FABRICANTE` varchar(254) NOT NULL,
	`CNPJ_FABRICANTE` varchar(19) NOT NULL,
	`NUM_RUA_FABRICANTE` bigint NOT NULL,
	`ENDERECO_FABRICANTE` varchar(150) NOT NULL,
	`TELEFONE_FABRICANTE` varchar(12) NOT NULL,
	`EMAIL_FABRICANTE` varchar(50) NOT NULL,
	`OBSERVACAO_FABRICANTE` varchar(250),
	PRIMARY KEY (`ID_FABRICANTE`)
);

CREATE TABLE `ESTOQUE` (
	`ID_ESTOQUE` bigint NOT NULL AUTO_INCREMENT,
	`EAE_PRODUTO` bigint NOT NULL,
	`NOME_PRODUTO` varchar(100) NOT NULL,
	`PRECO_PRODUTO` FLOAT NOT NULL,
	`CUSTO_PRODUTO` FLOAT NOT NULL,
	`VALIDADE_PRODUTO` DATE NOT NULL,
	`FABRICACAO_PRODUTO` DATE NOT NULL,
	`ID_FABRICANTE` bigint NOT NULL,
	PRIMARY KEY (`ID_ESTOQUE`)
);

ALTER TABLE `PESSOA_FISICA` ADD CONSTRAINT `PESSOA_FISICA_fk0` FOREIGN KEY (`LOJA_FUNC`) REFERENCES `LOJAS`(`ID_LOJA`);

ALTER TABLE `FUNCIONARIO` ADD CONSTRAINT `FUNCIONARIO_fk0` FOREIGN KEY (`ID_FUNC`) REFERENCES `PESSOA_FISICA`(`ID_PI`);

ALTER TABLE `CARGO` ADD CONSTRAINT `CARGO_fk0` FOREIGN KEY (`ID_CARGO`) REFERENCES `PESSOA_FISICA`(`ID_PI`);

ALTER TABLE `LOGIN_LOJA` ADD CONSTRAINT `LOGIN_LOJA_fk0` FOREIGN KEY (`ID_LOGIN`) REFERENCES `LOJAS`(`ID_LOJA`);

ALTER TABLE `PRODUTO` ADD CONSTRAINT `PRODUTO_fk0` FOREIGN KEY (`ID_PRODUTO`) REFERENCES `ESTOQUE`(`ID_ESTOQUE`);

ALTER TABLE `ESTOQUE` ADD CONSTRAINT `ESTOQUE_fk0` FOREIGN KEY (`ID_FABRICANTE`) REFERENCES `FABRICANTE`(`ID_FABRICANTE`);











